// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpimqcffcuikjgguqngz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwaW1xY2ZmY3Vpa2pnZ3Vxbmd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDIwNjMsImV4cCI6MjA2MTkxODA2M30.p9JwRxrJd8CVPo_L6LoQXhRuSugYVbGPNFktATkDuEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});